Add rsync
geshan/docker-fabric-alpine pull request #4
Opened 2016-12-29 11:49 UTC by enm10k

Add rsync for `fabric.contrib.project.rsync_project`.
http://docs.fabfile.org/en/1.12/api/contrib/project.html#fabric.contrib.project.rsync_project

2017-01-04 05:22 UTC, geshan requested changes

2017-01-04 05:22 UTC, geshan commented on Dockerfile
> +    apk add --no-cache fabric --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
please add back `rm /var/cache/apk/*` and rebase with latest master.

2017-01-06 16:18 UTC, enm10k commented on Dockerfile
> +    apk add --no-cache fabric --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
> please add back rm /var/cache/apk/* 

Thanks to `--no-cache` option, no need to `rm /var/cache/apk/*`.
You can check it like this.
`docker run -it cc01a56f105d ls /var/cache/apk`

> rebase with latest master.

Understood. I will ping you when it's finished.

Thank you.

2017-01-06 16:31 UTC, enm10k commented on Dockerfile
> +    apk add --no-cache fabric --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
@geshan Done. Please check it.

2017-01-06 16:33 UTC, geshan approved these changes
Merging

2017-01-06 16:33 UTC, merged

2017-01-06 16:39 UTC, enm10k commented
Thanks.

2017-01-06 16:40 UTC, geshan commented
Welcome

Warm Regards,
Geshan Manandhar

On Jan 6, 2017 20:39, "enm10k" <notifications@github.com> wrote:

> Thanks.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/geshan/docker-fabric-alpine/pull/4#issuecomment-270944699>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKaOupAsH5lLkeboqc0WkXXbcd399l2ks5rPm5egaJpZM4LXh-I>
> .
>